kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: kafka
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: statefulset
    name: kafka 
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: "kafka-metrics"
      targetAverageValue: 5
